# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
                ('used_project', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chiller',
            fields=[
                ('basicinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.BasicInfo')),
                ('capacity', models.IntegerField(blank=True)),
                ('cop', models.FloatField(blank=True)),
                ('chwtemp', models.FloatField(blank=True)),
                ('conwtemp', models.FloatField(blank=True)),
                ('chwfr', models.FloatField(blank=True, null=True)),
                ('conwfr', models.FloatField(blank=True, null=True)),
                ('minplr', models.FloatField(blank=True, null=True)),
                ('maxplr', models.FloatField(blank=True, null=True)),
                ('optimumplr', models.FloatField(blank=True, null=True)),
                ('minunloadratio', models.FloatField(blank=True, null=True)),
                ('condenser', models.CharField(choices=[('WaterCooled', 'WaterCooled'), ('AirCooled', 'AirCooled'), ('EvaporativelyCooled', 'EvaporativelyCooled')], default='WaterCooled', max_length=15)),
                ('flowmode', models.CharField(choices=[('ConstantFlow', 'ConstantFlow'), ('NotModulated', 'NotModulated'), ('LeavingSetpointModulated', 'LeavingSetpointModulated')], default='ConstantFlow', max_length=50)),
            ],
            bases=('HVAC.basicinfo',),
        ),
        migrations.CreateModel(
            name='FCU',
            fields=[
                ('basicinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.BasicInfo')),
                ('AirVolume', models.IntegerField(blank=True)),
                ('SensibleCoolCap', models.IntegerField(blank=True)),
                ('LatentCoolCap', models.IntegerField(blank=True)),
                ('HeatCap', models.IntegerField(blank=True)),
                ('WaterFlow', models.IntegerField(blank=True)),
                ('Noise', models.IntegerField(blank=True)),
            ],
            bases=('HVAC.basicinfo',),
        ),
        migrations.CreateModel(
            name='HeatExchanger',
            fields=[
                ('basicinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.BasicInfo')),
                ('Efficiency', models.IntegerField(blank=True)),
                ('AirVolume', models.IntegerField(blank=True)),
                ('Noise', models.IntegerField(blank=True)),
                ('Consumption', models.IntegerField(blank=True)),
            ],
            bases=('HVAC.basicinfo',),
        ),
        migrations.CreateModel(
            name='VRV',
            fields=[
                ('basicinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.BasicInfo')),
                ('InletT', models.FloatField(blank=True)),
                ('OutletT', models.FloatField(blank=True)),
                ('Capacity', models.IntegerField(blank=True)),
                ('COP', models.FloatField(blank=True)),
            ],
            bases=('HVAC.basicinfo',),
        ),
        migrations.CreateModel(
            name='CapacityFunction',
            fields=[
                ('chiller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HVAC.Chiller')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('c1', models.FloatField()),
                ('c2', models.FloatField()),
                ('c3', models.FloatField()),
                ('c4', models.FloatField()),
                ('c5', models.FloatField()),
                ('c6', models.FloatField()),
                ('min_x', models.FloatField(blank=True)),
                ('max_x', models.FloatField(blank=True)),
                ('min_y', models.FloatField(blank=True)),
                ('max_y', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EIRofPLR',
            fields=[
                ('chiller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HVAC.Chiller')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('c1', models.FloatField()),
                ('c2', models.FloatField()),
                ('c3', models.FloatField()),
                ('c4', models.FloatField(blank=True, null=True)),
                ('min_x', models.FloatField(blank=True)),
                ('max_x', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EIRofTemp',
            fields=[
                ('chiller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HVAC.Chiller')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('c1', models.FloatField()),
                ('c2', models.FloatField()),
                ('c3', models.FloatField()),
                ('c4', models.FloatField()),
                ('c5', models.FloatField()),
                ('c6', models.FloatField()),
                ('min_x', models.FloatField(blank=True)),
                ('max_x', models.FloatField(blank=True)),
                ('min_y', models.FloatField(blank=True)),
                ('max_y', models.FloatField(blank=True)),
            ],
        ),
    ]
