# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='used_project',
        ),
    ]
