# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacityfunction',
            name='chiller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cap', serialize=False, to='HVAC.Chiller'),
        ),
        migrations.AlterField(
            model_name='eirofplr',
            name='chiller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eirplr', serialize=False, to='HVAC.Chiller'),
        ),
        migrations.AlterField(
            model_name='eiroftemp',
            name='chiller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eirtemp', serialize=False, to='HVAC.Chiller'),
        ),
    ]
