# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0002_remove_basicinfo_used_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='used_project',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
