# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0004_auto_20160514_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chiller',
            name='Capacity',
            field=models.IntegerField(blank=True),
        ),
    ]
