# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-30 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0006_basicinfo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chiller',
            name='COP',
            field=models.FloatField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chiller',
            name='Condenser',
            field=models.CharField(choices=[('WaterCooled', 'WaterCooled'), ('AirCooled', 'AirCooled'), ('EvaporativelyCooled', 'EvaporativelyCooled')], default='Water', max_length=15),
        ),
        migrations.AddField(
            model_name='chiller',
            name='InletT',
            field=models.FloatField(blank=True, default=29),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chiller',
            name='OutletT',
            field=models.FloatField(blank=True, default=7),
            preserve_default=False,
        ),
    ]
