# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0008_auto_20170730_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.FloatField()),
                ('c2', models.FloatField()),
                ('c3', models.FloatField()),
                ('c4', models.FloatField()),
                ('c5', models.FloatField()),
                ('c6', models.FloatField()),
                ('minX', models.FloatField(blank=True)),
                ('maxX', models.FloatField(blank=True)),
                ('minY', models.FloatField(blank=True)),
                ('maxY', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EIRofPLR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.FloatField()),
                ('c2', models.FloatField()),
                ('c3', models.FloatField()),
                ('c4', models.FloatField()),
                ('minX', models.FloatField(blank=True)),
                ('maxX', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FCU',
            fields=[
                ('basicinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.BasicInfo')),
                ('AirVolume', models.IntegerField(blank=True)),
                ('SensibleCoolCap', models.IntegerField(blank=True)),
                ('LatentCoolCap', models.IntegerField(blank=True)),
                ('HeatCap', models.IntegerField(blank=True)),
                ('WaterFlow', models.IntegerField(blank=True)),
                ('Noise', models.IntegerField(blank=True)),
            ],
            bases=('HVAC.basicinfo',),
        ),
        migrations.AddField(
            model_name='chiller',
            name='CHWFlowRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chiller',
            name='CWFlowRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chiller',
            name='maxPLR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chiller',
            name='minPLR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chiller',
            name='minUnloadRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chiller',
            name='optimumPLR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EIRofTemp',
            fields=[
                ('capacityfunction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.CapacityFunction')),
            ],
            bases=('HVAC.capacityfunction',),
        ),
        migrations.AddField(
            model_name='chiller',
            name='CapacityFunction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cap', to='HVAC.CapacityFunction'),
        ),
        migrations.AddField(
            model_name='chiller',
            name='EIRofPLR',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eirplr', to='HVAC.EIRofPLR'),
        ),
        migrations.AddField(
            model_name='chiller',
            name='EIRofTemp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eirtemp', to='HVAC.EIRofTemp'),
        ),
    ]
