# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0010_auto_20180127_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
