# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0011_auto_20180127_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
