# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0012_auto_20180127_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eirofplr',
            name='c4',
            field=models.FloatField(blank=True),
        ),
    ]
