# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0014_auto_20180127_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='used_project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
