# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0015_auto_20180127_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chiller',
            name='vrv_ptr',
        ),
        migrations.AddField(
            model_name='chiller',
            name='basicinfo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.BasicInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chiller',
            name='capacity',
            field=models.IntegerField(blank=True, default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chiller',
            name='chwtemp',
            field=models.FloatField(blank=True, default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chiller',
            name='cop',
            field=models.FloatField(blank=True, default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chiller',
            name='cwtemp',
            field=models.FloatField(blank=True, default=28),
            preserve_default=False,
        ),
    ]
