# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0016_auto_20180128_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chiller',
            old_name='Condenser',
            new_name='condenser',
        ),
        migrations.RenameField(
            model_name='chiller',
            old_name='maxPLR',
            new_name='maxplr',
        ),
        migrations.RenameField(
            model_name='chiller',
            old_name='minPLR',
            new_name='minplr',
        ),
        migrations.RenameField(
            model_name='chiller',
            old_name='optimumPLR',
            new_name='optimumplr',
        ),
    ]
