# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0017_auto_20180128_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chiller',
            old_name='CapacityFunction',
            new_name='capfunc',
        ),
        migrations.RenameField(
            model_name='chiller',
            old_name='EIRofPLR',
            new_name='eirofplr',
        ),
        migrations.RenameField(
            model_name='chiller',
            old_name='EIRofTemp',
            new_name='eiroftemp',
        ),
    ]
