# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0018_auto_20180128_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capacityfunction',
            old_name='maxX',
            new_name='max_x',
        ),
        migrations.RenameField(
            model_name='capacityfunction',
            old_name='maxY',
            new_name='max_y',
        ),
        migrations.RenameField(
            model_name='capacityfunction',
            old_name='minX',
            new_name='min_x',
        ),
        migrations.RenameField(
            model_name='capacityfunction',
            old_name='minY',
            new_name='min_y',
        ),
        migrations.RenameField(
            model_name='eirofplr',
            old_name='maxX',
            new_name='max_x',
        ),
        migrations.RenameField(
            model_name='eirofplr',
            old_name='minX',
            new_name='min_x',
        ),
    ]
