# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0019_auto_20180128_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiller',
            name='flowmode',
            field=models.CharField(choices=[('ConstantFlow', 'ConstantFlow'), ('NotModulated', 'NotModulated'), ('LeavingSetpointModulated', 'LeavingSetpointModulated')], default='ConstantFlow', max_length=50),
        ),
        migrations.AlterField(
            model_name='chiller',
            name='condenser',
            field=models.CharField(choices=[('WaterCooled', 'WaterCooled'), ('AirCooled', 'AirCooled'), ('EvaporativelyCooled', 'EvaporativelyCooled')], default='WaterCooled', max_length=15),
        ),
    ]
