# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0020_auto_20180130_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chiller',
            old_name='CHWFlowRate',
            new_name='chwfr',
        ),
        migrations.RenameField(
            model_name='chiller',
            old_name='CWFlowRate',
            new_name='conwfr',
        ),
        migrations.RenameField(
            model_name='chiller',
            old_name='cwtemp',
            new_name='conwtemp',
        ),
        migrations.RenameField(
            model_name='chiller',
            old_name='minUnloadRatio',
            new_name='minunloadratio',
        ),
    ]
