# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0021_auto_20180130_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chiller',
            name='capfunc',
        ),
        migrations.RemoveField(
            model_name='chiller',
            name='eirofplr',
        ),
        migrations.RemoveField(
            model_name='chiller',
            name='eiroftemp',
        ),
        migrations.AddField(
            model_name='capacityfunction',
            name='chiller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HVAC.Chiller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eirofplr',
            name='chiller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HVAC.Chiller'),
            preserve_default=False,
        ),
    ]
