# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0022_auto_20180130_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eiroftemp',
            name='capacityfunction_ptr',
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='c1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='c2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='c3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='c4',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='c5',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='c6',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='chiller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='eirtemp', to='HVAC.Chiller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='max_x',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='max_y',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='min_x',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='min_y',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eiroftemp',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='capacityfunction',
            name='chiller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap', to='HVAC.Chiller'),
        ),
        migrations.AlterField(
            model_name='eirofplr',
            name='chiller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eirplr', to='HVAC.Chiller'),
        ),
    ]
