# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HVAC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lighting',
            fields=[
                ('basicinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.BasicInfo')),
                ('lamp_type', models.CharField(blank=True, max_length=50)),
                ('wattage', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('mercury', models.FloatField(blank=True, null=True)),
                ('color_temp', models.IntegerField(blank=True, null=True)),
                ('cri', models.IntegerField(blank=True, null=True)),
                ('flux', models.FloatField(blank=True, null=True)),
                ('efficacy', models.FloatField(blank=True, null=True)),
            ],
            bases=('HVAC.basicinfo',),
        ),
    ]
