# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lighting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting',
            name='efficacy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='flux',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='mercury',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='voltage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='wattage',
            field=models.FloatField(),
        ),
    ]
