# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lighting', '0002_auto_20160420_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighting',
            name='cri',
            field=models.IntegerField(blank=True, default=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lighting',
            name='color_temp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='efficacy',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='flux',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='lamp_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='mercury',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='voltage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='wattage',
            field=models.FloatField(blank=True),
        ),
    ]
