# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HVAC', '0003_basicinfo_used_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('basicinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.BasicInfo')),
                ('thickness', models.IntegerField()),
                ('tsol', models.FloatField()),
                ('rsol1', models.FloatField()),
                ('rsol2', models.FloatField()),
                ('tvis', models.FloatField()),
                ('rvis1', models.FloatField()),
                ('rvis2', models.FloatField()),
                ('emis1', models.FloatField()),
                ('emis2', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('tvis2', models.FloatField()),
                ('tsol2', models.FloatField()),
            ],
            bases=('HVAC.basicinfo',),
        ),
    ]
