# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HVAC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('basicinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.BasicInfo')),
                ('thickness', models.FloatField(blank=True, null=True)),
                ('tsol', models.FloatField(blank=True, null=True)),
                ('rsol1', models.FloatField(blank=True, null=True)),
                ('rsol2', models.FloatField(blank=True, null=True)),
                ('tvis', models.FloatField(blank=True, null=True)),
                ('rvis1', models.FloatField(blank=True, null=True)),
                ('rvis2', models.FloatField(blank=True, null=True)),
                ('emis1', models.FloatField(blank=True, null=True)),
                ('emis2', models.FloatField(blank=True, null=True)),
                ('conductivity', models.FloatField(blank=True, null=True)),
                ('tvis2', models.FloatField(blank=True, null=True)),
                ('tsol2', models.FloatField(blank=True, null=True)),
            ],
            bases=('HVAC.basicinfo',),
        ),
        migrations.CreateModel(
            name='Insulation',
            fields=[
                ('basicinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.BasicInfo')),
                ('conductivity', models.FloatField(blank=True)),
                ('lcc', models.FloatField(blank=True)),
            ],
            bases=('HVAC.basicinfo',),
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thick', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='insulation',
            name='thickness',
            field=models.ManyToManyField(blank=True, to='Envelope.Thickness'),
        ),
    ]
