# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envelope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass',
            name='conductivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='emis1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='emis2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='rsol1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='rsol2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='rvis1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='rvis2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='thickness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='tsol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='tsol2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='tvis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='tvis2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
