# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-30 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HVAC', '0007_auto_20170730_1806'),
        ('Envelope', '0003_auto_20160514_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insulation',
            fields=[
                ('basicinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HVAC.BasicInfo')),
                ('conductivity', models.FloatField(blank=True)),
                ('lcc', models.FloatField(blank=True)),
            ],
            bases=('HVAC.basicinfo',),
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thick', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='insulation',
            name='thickness',
            field=models.ManyToManyField(blank=True, to='Envelope.Thickness'),
        ),
    ]
